name: ekyc
description: Demo Ekyc SoftDreams

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: "3.0.1"

dependencies:
  app_settings: ^4.1.0
  auto_size_text: ^3.0.0
  camera: ^0.10.0+5
  circular_countdown_timer: ^0.2.1
  device_info_plus: ^8.0.0
  dio: ^4.0.0
  dmrtd:
    git:
      url: https://github.com/ZeroPass/dmrtd.git
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_cupertino_datetime_picker: ^3.0.0
  flutter_image_compress: ^1.1.0
  flutter_inappwebview: ^5.7.2+3
  flutter_launcher_icons: ^0.11.0
  flutter_localizations:
    sdk: flutter
  fluttertoast: 8.0.7
  gallery_saver: ^2.3.2
  get: 4.3.8
  get_storage: ^2.0.2
  hex: ^0.2.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  image: ^3.1.1
  intl: ^0.17.0
  loading_overlay_pro: ^2.1.1
  path_provider: ^2.0.15
  permission_handler: any
  pinput: ^2.2.20
  pull_to_refresh: ^2.0.0
  qr_code_scanner: ^1.0.1
  sds_flutter: ^1.0.0+6
  shimmer: ^2.0.0

flutter_icons:
  image_path_android: "assets/images/logo_ekyc.png"
  image_path_ios: "assets/images/logo_ekyc.png"
  android: ic_launcher # can specify file name here e.g. "ic_launcher"
  ios: My-Launcher-Icon # can specify file name here e.g. "My-Launcher-Icon"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo_ekyc.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo_ekyc.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo_ekyc.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/background/
    - assets/fonts/
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #  - family: Schyler
  #    fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
